---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
    type: local
    tier: database
type: Opaque
data:
  database: d29yZHByZXNzX2Ri
  password: d29yZHByZXNzMTIz
  user: d29yZHByZXNz
