---
apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  labels:
    app: wordpress
    tier: frontend
type: Opaque
data:
  database: d29yZHByZXNzX2Ri
  password: d29yZHByZXNzMTIz
  user: d29yZHByZXNz
