---
apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  labels:
    app: wordpress
    tier: frontend
type: Opaque
data:
  password: cGFzc3dvcmQK
  user: d29yZHByZXNzCg==
  database: d29yZHByZXNzCg==
